%define crate rio
%define appid com.rioterm.Rio

Name:           rio
Version:        0.5.5
Release:        1
Summary:        Hardware accelerated terminal emulator
License:        MIT and Apache-2.0 and BSD
URL:            https://rioterm.com/
Source0:        https://github.com/raphamorim/rio/archive/refs/tags/v%{version}/rio-%{version}.tar.gz

# Vendor generated by command: 'cargo vendor' inside source tree.
Source1:        vendor.tar.xz

BuildRequires:  cmake
BuildRequires:  desktop-file-utils
BuildRequires:  glslc
BuildRequires:  pkgconfig(alsa)
BuildRequires:	pkgconfig(expat)
BuildRequires:  pkgconfig(fontconfig)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(xcb)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:	rust-packaging
# (angry p) needed in case of Nvidia on Wayland and usage OpenGL as the main backend.
BuildRequires:	egl-devel

Requires:       fontconfig
Requires:       hicolor-icon-theme
Requires:       ncurses

%description
Hardware accelerated terminal emulator written in Rust.

%prep
%autosetup -n rio-%{version} -p1 -a 1

%cargo_prep -v vendor

#mkdir -p .cargo
#cat > .cargo/config.toml << EOF
#[source.crates-io]
#replace-with = "vendored-sources"

#[source.vendored-sources]
#directory = "vendor"
#EOF

sed -i 's|Exec=.*|Exec=rio|g' misc/rio.desktop

%build
#cargo build --release --locked
%cargo_build

%install
#cargo_install
install -Dm755 target/rpm/%{name} \
    %{buildroot}%{_bindir}/%{crate}

install -Dm755 target/release/librio_backend.so \
    %{buildroot}%{_libdir}/librio_backend.so

install -Dm755 target/release/libsugarloaf.so \
    %{buildroot}%{_libdir}/libsugarloaf.so
    
install -Dm644 misc/logo.svg \
    %{buildroot}%{_iconsdir}/hicolor/scalable/apps/rio.svg

install -Dm644 misc/%{appid}.metainfo.xml \
    %{buildroot}%{_metainfodir}/%{appid}.metainfo.xml

desktop-file-install \
    --dir=%{buildroot}%{_datadir}/applications \
    misc/rio.desktop

%files 
%{_bindir}/%{crate}
%{_libdir}/librio_backend.so*
%{_libdir}/libsugarloaf.so*
%{_datadir}/applications/%{name}.desktop
%{_iconsdir}/hicolor/scalable/apps/%{name}.svg
%{_metainfodir}/%{appid}.metainfo.xml
